// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIH23s_43g2XuLuhMcJVeSA40T5FRbyE',
    appId: '1:238478735854:web:3106778290b739325936ff',
    messagingSenderId: '238478735854',
    projectId: 'myauth-3afa4',
    authDomain: 'myauth-3afa4.firebaseapp.com',
    storageBucket: 'myauth-3afa4.appspot.com',
    measurementId: 'G-3H21JRYDSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VvaWZTc_2RK4I39R1-buJQcqYqOdaUQ',
    appId: '1:238478735854:android:327c50c10f5af2d05936ff',
    messagingSenderId: '238478735854',
    projectId: 'myauth-3afa4',
    storageBucket: 'myauth-3afa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eoDj5nK7UUB9VE9RD9O2nYdNRQk-kKs',
    appId: '1:238478735854:ios:a85b45945a29411c5936ff',
    messagingSenderId: '238478735854',
    projectId: 'myauth-3afa4',
    storageBucket: 'myauth-3afa4.appspot.com',
    androidClientId: '238478735854-ds8jofrvqnvpegamsqaoakio57qba25k.apps.googleusercontent.com',
    iosClientId: '238478735854-laha7sfq33u76jo0u5ftfk14cgobfrjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.myauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_eoDj5nK7UUB9VE9RD9O2nYdNRQk-kKs',
    appId: '1:238478735854:ios:a85b45945a29411c5936ff',
    messagingSenderId: '238478735854',
    projectId: 'myauth-3afa4',
    storageBucket: 'myauth-3afa4.appspot.com',
    androidClientId: '238478735854-ds8jofrvqnvpegamsqaoakio57qba25k.apps.googleusercontent.com',
    iosClientId: '238478735854-laha7sfq33u76jo0u5ftfk14cgobfrjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.myauth',
  );
}
